-- RMO Compliance — Supabase Auth cutover notes (no schema changes required)
--
-- Auth credentials live in auth.users. App authorization stays on public.users
-- + public.user_licenses, linked by public.users.auth_user_id.
--
-- Ops after deploy:
-- 1. Supabase Dashboard → Authentication → URL Configuration
--      Site URL: https://rmo.buildmyoffice.com
--      Redirect allow list:
--        https://rmo.buildmyoffice.com/**
--        http://localhost:3000/**
-- 2. Create / set password for jbeachum@buildmyoffice.com (Dashboard Users,
--    scripts/bootstrap-supabase-auth.mjs, legacy password auto-migrate on
--    first login, or Forgot password → reset email).
-- 3. Unset PILOT_PASSWORD on Vercel (deprecated; no longer read for login).
-- 4. Redirect allow list must include /auth/reset-password (+ /auth/confirm).
--
-- No new public tables in this cutover — Data API GRANTs unchanged.
-- (If you add public tables later, GRANT SELECT to anon; GRANT SELECT,
--  INSERT, UPDATE, DELETE to authenticated and service_role.)

SELECT 1;
